### ISSUE TITLE
can no install, python version error, node-sass

### ISSUE THREAD

**Issue by bueno12223** [nguyenvanduocit/vue-loading-spinner#44]
I have the next issue al run npm install
```npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /mnt/c/Users/berri/projects/foro4/foro4/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /home/jesus/.nvm/versions/node/v16.14.2/bin/node /mnt/c/Users/berri/projects/foro4/foro4/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/home/jesus/.nvm/versions/node/v16.14.2/bin/node',
npm ERR! gyp verb cli   '/mnt/c/Users/berri/projects/foro4/foro4/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.14.2 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "C:\Python27\python.exe" in the PATH
npm ERR! gyp verb `which` failed Error: not found: C:\Python27\python.exe
npm ERR! gyp verb `which` failed     at getNotFoundError (/mnt/c/Users/berri/projects/foro4/foro4/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/mnt/c/Users/berri/projects/foro4/foro4/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/mnt/c/Users/berri/projects/foro4/foro4/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /mnt/c/Users/berri/projects/foro4/foro4/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /mnt/c/Users/berri/projects/foro4/foro4/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /mnt/c/Users/berri/projects/foro4/foro4/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  C:\Python27\python.exe Error: not found: C:\Python27\python.exe
npm ERR! gyp verb `which` failed     at getNotFoundError (/mnt/c/Users/berri/projects/foro4/foro4/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/mnt/c/Users/berri/projects/foro4/foro4/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/mnt/c/Users/berri/projects/foro4/foro4/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /mnt/c/Users/berri/projects/foro4/foro4/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /mnt/c/Users/berri/projects/foro4/foro4/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /mnt/c/Users/berri/projects/foro4/foro4/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "C:\Python27\python.exe", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/mnt/c/Users/berri/projects/foro4/foro4/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/mnt/c/Users/berri/projects/foro4/foro4/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/mnt/c/Users/berri/projects/foro4/foro4/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/mnt/c/Users/berri/projects/foro4/foro4/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /mnt/c/Users/berri/projects/foro4/foro4/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /mnt/c/Users/berri/projects/foro4/foro4/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /mnt/c/Users/berri/projects/foro4/foro4/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Linux 4.4.0-19041-Microsoft
npm ERR! gyp ERR! command "/home/jesus/.nvm/versions/node/v16.14.2/bin/node" "/mnt/c/Users/berri/projects/foro4/foro4/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /mnt/c/Users/berri/projects/foro4/foro4/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jesus/.npm/_logs/2022-05-29T20_31_34_535Z-debug-0.log```

In base a [this](https://stackoverflow.com/questions/45801457/node-js-python-not-found-exception-due-to-node-sass-and-node-gyp) stackoverflow issue, yuo are using the version of node-sass 4.5.3 that use python 2.
Yes, is possible install and change the path of python to the version 3, but like a developer is uncomfortable.
My recomedation is update node-sass to the lastes version

**Comment by vincent-xw** [comment]
my fork version fixed this problem

**Comment by nguyenvanduocit** [comment]
I am rewrite it
